package Shared.Requests;

public enum Request {
    GET_PRODUCT_LIST,
    USER_LOGIN,
    USER_REGISTER,
    ADMIN_LOGIN,
    ADMIN_INSERT_PRODUCT,
    ADMIN_MODIFY_PRODUCT,
    ADMIN_RECOMMENDS,
    USER_GET_RECOMMENDATION,
    ADMIN_GET_SALES,
    ADMIN_GET_USER_TOP_SALE,
    USER_CHECKOUT,
    TEST
}
